### ISSUE TITLE
Licencja

### ISSUE THREAD

**Issue by HichuYamichu** [Maathias/rolniknysa#1]
Wlepiamy MIT i mamy to w dupie czy bawimy się w Apache 2 albo inne GPL?

**Comment by Maathias** [comment]
Myśle że mit/gpl obojętnie. I tak to nikogo za bardzo nie będzie obchodzić

**Comment by HichuYamichu** [comment]
Galinux się ucieszy jak zobaczy Open Source'ową licencje xD
Dobra to przyklepie MITa i zamykam
